import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/HomeComponents/Navbar/Navbar";
import { ReduxProvider } from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amazon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="sticky top-0 bg-[#131921] z-10">
            <Navbar />
          </div>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
